### ISSUE TITLE
 Unable to resolve realm public key remotely

### ISSUE THREAD

**Issue by stefanorg** [atomsd/atoms#1]
Afeter a fresh installation of a deb package 1.1.3.final
Trying to access: `http://<myip>/atoms`   i get this error. How i'm supposed to access atomsd user interface?

```
2016-07-02_15:01:44.57920 ^[[0m^[[31m17:24:33,783 ERROR [io.undertow.request] (default task-13) UT005023: Exception handling request to /atoms/index.html: java.lang.RuntimeException: Unable to resolve realm public key remotely, status = 404
2016-07-02_15:24:33.78455       at org.keycloak.adapters.AdapterDeploymentContext.resolveRealmKey(AdapterDeploymentContext.java:110) [keycloak-adapter-core-1.5.1.Final.jar:1.5.1.Final]
2016-07-02_15:24:33.78456       at org.keycloak.adapters.AdapterDeploymentContext.resolveDeployment(AdapterDeploymentContext.java:84) [keycloak-adapter-core-1.5.1.Final.jar:1.5.1.Final]
2016-07-02_15:24:33.78458       at org.keycloak.adapters.PreAuthActionsHandler.preflightCors(PreAuthActionsHandler.java:71) [keycloak-adapter-core-1.5.1.Final.jar:1.5.1.Final]
2016-07-02_15:24:33.78459       at org.keycloak.adapters.PreAuthActionsHandler.handleRequest(PreAuthActionsHandler.java:47) [keycloak-adapter-core-1.5.1.Final.jar:1.5.1.Final]
2016-07-02_15:24:33.78460       at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:68) [keycloak-undertow-adapter-1.5.1.Final.jar:1.5.1.Final]
2016-07-02_15:24:33.78460       at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
2016-07-02_15:24:33.78461       at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
2016-07-02_15:24:33.78462       at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:248) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
2016-07-02_15:24:33.78462       at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:77) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
2016-07-02_15:24:33.78464       at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:167) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
2016-07-02_15:24:33.78465       at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
2016-07-02_15:24:33.78465       at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:761) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
```

**Comment by atomsd** [comment]
Hi stefanorg, can you post the the application log /var/log/atoms/atoms-server/current
Further more which linux distro/version are you using?

**Comment by stefanorg** [comment]
Hi, i'm using:

```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

The log is attached, thanks for support. i couldn't find any documentation on the website..
[current.txt](https://github.com/atomsd/atoms/files/345261/current.txt)

.

**Comment by atomsd** [comment]
hi, due to system logrotate current.txt doesn't contain any useful information.
can you restart the service and resend the log?
`sudo atomsd-ctl restart`

You can also check that system is configured properly:
Server installation documentation is available [here](https://github.com/atomsd/omnibus-atoms/blob/master/doc/settings/configuration.md) while configuration options are available [here](https://github.com/atomsd/omnibus-atoms/blob/master/doc/settings/configuration.md)

**Comment by stefanorg** [comment]
ok, restarted the service ...
[current.txt](https://github.com/atomsd/atoms/files/345305/current.txt)

**Comment by atomsd** [comment]
According to the log server is running properly now.
Can you retry to access the server?

**Comment by stefanorg** [comment]
accessing from the public dns of the server, the problem persist, so i did:
1) lynx http://localhost/atoms
and i see a page (not lynx compliant :dancer: of course)
2) retry access from public dns http://myserver/atoms

and now it works. In log i can't see nothing special...

**Comment by atomsd** [comment]
Great, REST api documentation is available [here](http://atomsd.org/documentation/server/rest-api/).
Furthermore, AeroGear Clients are also supported [http://atomsd.org/documentation/](http://atomsd.org/documentation/).
